FROM localhost:5000/admin/golang:1.5.4

# Set the default timezone to Shanghai
RUN echo "Asia/Shanghai" > /etc/timezone
RUN dpkg-reconfigure -f noninteractive tzdata

# Copy Testcase
WORKDIR /root
COPY ./TestCase /root

CMD ["/root/TestCase"]
